import {chromium} from 'playwright';import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,channel:'chrome'});const ctxA=await browser.newContext(),ctxB=await browser.newContext();const a=await ctxA.newPage(),b=await ctxB.newPage();const errors=[];for(const p of [a,b])p.on('pageerror',e=>errors.push(e.message));
try{
await a.goto('http://localhost:4173/#multiplayer');await a.fill('#host-name','Host');await a.selectOption('#rounds','4');await a.click('#create-room button');await a.locator('.room-code').waitFor();const code=await a.locator('.room-code').evaluate(el=>el.firstChild.textContent.trim());assert.equal(await a.locator('#start-party').isDisabled(),true);
await b.goto('http://localhost:4173/#room/'+code);await b.fill('#guest-name','Guest');await b.click('#join-room button');await b.locator('.room-code').waitFor();await a.waitForFunction(()=>document.querySelector('#start-party')?.disabled===false);await a.click('#start-party');await a.locator('.secret-chapter').waitFor();await b.locator('.guess-prompt').waitFor();const secret1=await a.locator('.secret-chapter h2').innerText();assert.equal(await b.locator('.secret-chapter').count(),0);
// Invalid clue stays in the input and displays a readable error.
await a.fill('#room-message',secret1);await a.click('#send-message');await a.waitForFunction(()=>document.querySelector('#room-error')?.textContent.includes('secret'));assert.equal(await a.inputValue('#room-message'),secret1);
await a.fill('#room-message','Think about the people and the events in this story.');await a.click('#send-message');await b.getByText('Think about the people and the events in this story.',{exact:true}).waitFor();
// Polling must not disrupt typing.
await b.fill('#room-message','An unfinished draft');await b.waitForTimeout(1600);assert.equal(await b.inputValue('#room-message'),'An unfinished draft');await b.fill('#room-message',secret1);await b.click('#send-message');await b.locator('.reveal-card').waitFor();await a.locator('.reveal-card').waitFor();assert.match(await b.locator('#room-players').innerText(),/100/);assert.match(await a.locator('#room-players').innerText(),/40/);
console.log('Round 1 passed');await a.click('[data-action="next"]');await b.locator('.secret-chapter').waitFor();await a.locator('.guess-prompt').waitFor();assert.equal(await a.locator('.secret-chapter').count(),0);const secret2=await b.locator('.secret-chapter h2').innerText();assert.notEqual(secret2,secret1);await b.reload();await b.locator('.secret-chapter').waitFor();assert.equal(await b.locator('.secret-chapter h2').innerText(),secret2);
await a.fill('#room-message',secret2);await a.click('#send-message');await a.locator('.reveal-card').waitFor();await a.click('[data-action="next"]');await a.locator('.secret-chapter').waitFor();let answer=await a.locator('.secret-chapter h2').innerText();await b.locator('.guess-prompt').waitFor();await b.fill('#room-message',answer);await b.click('#send-message');await a.locator('.reveal-card').waitFor();console.log('Round 1 passed');await a.click('[data-action="next"]');await b.locator('.secret-chapter').waitFor();answer=await b.locator('.secret-chapter h2').innerText();await a.locator('.guess-prompt').waitFor();await a.fill('#room-message',answer);await a.click('#send-message');await a.locator('[data-action="next"]').waitFor();await a.click('[data-action="next"]');await a.locator('[data-action="rematch"]').waitFor();await b.getByText('A good game, together.',{exact:true}).waitFor();await a.screenshot({path:'/tmp/kairos-party-result.png',fullPage:true});await a.click('[data-action="rematch"]');await a.locator('#start-party').waitFor();await b.waitForTimeout(1500);await a.click('[data-action="leave"]');await a.locator('#create-room').waitFor();await b.locator('#start-party').waitFor();assert.equal(await b.locator('#start-party').isDisabled(),true);assert.deepEqual(errors,[]);console.log('PASS two isolated clients: create/join, hidden answers, rejected clues, preserved typing, scoring, rotation, reload, complete match, rematch, host migration');
}catch(e){console.log('A',await a.locator('#party-root').innerText());console.log('B',await b.locator('#party-root').innerText());throw e;}finally{await browser.close();}
