import {createRoom,joinRoom,applyAction,roomView,expireRound} from './room-engine.mjs';
const response=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const hash=async text=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const secret=()=>{const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('');};
const newCode=()=>{const a=new Uint8Array(6);crypto.getRandomValues(a);return [...a].map(x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');};
class ApiError extends Error{constructor(message,status=400){super(message);this.status=status;}}
async function readRoom(db,code,now){const row=await db.prepare('SELECT state, revision FROM rooms WHERE code = ? AND expires_at > ?').bind(code,now).first();if(!row)throw new ApiError('Room not found or expired. Check the code or create a new room.',404);return {room:JSON.parse(row.state),revision:row.revision};}
async function updateRoom(db,code,fn,now){for(let attempt=0;attempt<8;attempt++){const {room,revision}=await readRoom(db,code,now);const result=await fn(room);const updated=await db.prepare('UPDATE rooms SET state = ?, revision = revision + 1 WHERE code = ? AND revision = ?').bind(JSON.stringify(result.room),code,revision).run();if(updated.meta.changes===1)return result.value;}throw new ApiError('The room is busy. Please try again.',409);}
async function rateLimit(db,request,action,now){const ip=request.headers.get('CF-Connecting-IP')||'local';const window=Math.floor(now/3600000);const key=await hash(`${action}:${ip}:${window}`);const row=await db.prepare('INSERT INTO rate_limits (key, count, expires_at) VALUES (?, 1, ?) ON CONFLICT(key) DO UPDATE SET count = count + 1 RETURNING count').bind(key,now+3600000).first();if(row.count>(action==='create'?12:80))throw new ApiError('Too many rooms or joins in a short time. Try again later.',429);}
async function authenticate(request,room){const token=(request.headers.get('Authorization')||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))throw new ApiError('Rejoin this room to continue.',401);const tokenHash=await hash(token);const player=room.players.find(p=>p.tokenHash===tokenHash&&!p.left);if(!player)throw new ApiError('This room session is no longer active. Join again.',401);return player.id;}
export async function handleApi(request,env){try{const url=new URL(request.url),now=Date.now();if(url.pathname==='/api/health')return response({ok:true,multiplayer:!!env.DB});if(!env.DB)throw new ApiError('Multiplayer is temporarily unavailable. Please try again shortly.',503);const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)throw new ApiError('Please open the game on its own site.',403);let body={};if(request.method==='POST'){const raw=await request.text();if(raw.length>4096)throw new ApiError('That message is too long.',413);try{body=JSON.parse(raw);}catch{throw new ApiError('Invalid request.');}if(!body||typeof body!=='object'||Array.isArray(body))throw new ApiError('Invalid request.');}
if(url.pathname==='/api/rooms'&&request.method==='POST'){await rateLimit(env.DB,request,'create',now);await env.DB.batch([env.DB.prepare('DELETE FROM rooms WHERE code IN (SELECT code FROM rooms WHERE expires_at < ? LIMIT 100)').bind(now),env.DB.prepare('DELETE FROM rate_limits WHERE key IN (SELECT key FROM rate_limits WHERE expires_at < ? LIMIT 100)').bind(now)]);const token=secret(),tokenHash=await hash(token),id=crypto.randomUUID();for(let i=0;i<5;i++){const code=newCode(),room=createRoom(code,body.name,id,tokenHash,now,body.rounds);try{await env.DB.prepare('INSERT INTO rooms (code, state, revision, expires_at) VALUES (?, ?, 0, ?)').bind(code,JSON.stringify(room),room.expiresAt).run();return response({token,room:roomView(room,id,now)},201);}catch(e){if(!/UNIQUE/.test(String(e)))throw e;}}throw new ApiError('Could not create a room. Try again.',503);}
const match=url.pathname.match(/^\/api\/rooms\/([A-Z2-9]{6})(?:\/(join|action))?$/);if(!match)throw new ApiError('Not found.',404);const [,code,operation]=match;
if(operation==='join'&&request.method==='POST'){await rateLimit(env.DB,request,'join',now);const token=secret(),tokenHash=await hash(token),id=crypto.randomUUID();const view=await updateRoom(env.DB,code,room=>{const next=joinRoom(expireRound(room,now),body.name,id,tokenHash,now);return {room:next,value:roomView(next,id,now)};},now);return response({token,room:view},201);}
if(!operation&&request.method==='GET'){const {room,revision}=await readRoom(env.DB,code,now);const id=await authenticate(request,room);const current=expireRound(room,now);if(current.phase!==room.phase){const view=await updateRoom(env.DB,code,async r=>{const pid=await authenticate(request,r);const next=expireRound(r,now);return {room:next,value:roomView(next,pid,now)};},now);return response({room:view});}return response({room:roomView(current,id,now),revision});}
if(operation==='action'&&request.method==='POST'){if(typeof body.actionId!=='string'||!/^[a-zA-Z0-9-]{12,64}$/.test(body.actionId))throw new ApiError('This action needs a valid identifier.');const view=await updateRoom(env.DB,code,async room=>{const id=await authenticate(request,room);const receipt=id+':'+body.actionId;let current=expireRound(room,now);if(current.receipts.includes(receipt))return {room:current,value:roomView(current,id,now)};if(['guess','clue'].includes(body.type)&&body.round!==current.round)throw new ApiError('The round changed. Read the new clue and try again.',409);current=applyAction(current,id,body,now);current.receipts=[...current.receipts,receipt].slice(-100);return {room:current,value:body.type==='leave'?{left:true}:roomView(current,id,now)};},now);return response({room:view});}
throw new ApiError('Method not allowed.',405);
}catch(error){if(error instanceof ApiError)return response({error:error.message},error.status);if(/D1_|SQLITE|database|binding/i.test(String(error))){console.error('Room storage unavailable',String(error));return response({error:'The room service is temporarily unavailable. Your message is still here; try again.'},503);}return response({error:error.message||'The room could not be updated.'},400);}}
