// Server-only: never include the chapter deck in a public client bundle.
export const chapters=[
['creation','Genesis',1,'The beginning','Light, sky, land, plants, living creatures, and humanity appear in an ordered creation account.',['creation','light','image of God']],
['eden','Genesis',3,'The garden choice','A serpent questions God’s command. The humans eat the forbidden fruit, hide, and face the consequences.',['garden','serpent','forbidden fruit']],
['flood','Genesis',6,'Preparing an ark','Human wickedness grieves God. A righteous man is instructed to build a great vessel to preserve life.',['ark','wickedness','animals']],
['babel','Genesis',11,'A city and a tower','People build a city and a tower to make a name for themselves. Their language is confused and they scatter.',['tower','languages','scattering']],
['abraham','Genesis',12,'Called to go','A man is told to leave his homeland. God promises to bless him and make him a blessing to the nations.',['journey','promise','blessing']],
['joseph','Genesis',37,'Dreams and a robe','A father favours his son. His brothers resent his dreams and sell him to traders.',['dreams','robe','brothers']],
['burning','Exodus',3,'Fire that does not consume','A shepherd sees a bush burning without being consumed. God calls him to lead a people out of slavery.',['bush','holy ground','calling']],
['sea','Exodus',14,'A way through the water','An army pursues a fleeing people. The sea opens and they pass through on dry ground.',['sea','dry ground','deliverance']],
['commands','Exodus',20,'Words for a covenant people','God gives commands about worship, honouring parents, and how people are to treat one another.',['commands','covenant','neighbour']],
['jericho','Joshua',6,'Around the city','A people march around a fortified city, priests blow trumpets, and the walls fall.',['walls','trumpets','marching']],
['ruth','Ruth',1,'A loyal companion','A widowed woman stays with her mother-in-law, choosing her people and her God rather than returning home.',['loyalty','widows','Bethlehem']],
['goliath','1 Samuel',17,'An unlikely challenger','A young shepherd faces a giant warrior with a sling, trusting God rather than armour.',['giant','sling','courage']],
['shepherd','Psalm',23,'Care on the journey','A familiar poem pictures God as a shepherd, guiding beside still waters and accompanying the speaker through a dark valley.',['shepherd','still waters','valley']],
['refuge','Psalm',46,'A present help','A song declares God a refuge and strength even when mountains move and nations rage.',['refuge','strength','be still']],
['praise','Psalm',100,'An invitation to worship','People are called to serve with gladness and enter God’s gates with thanksgiving.',['gladness','thanksgiving','praise']],
['trust','Proverbs',3,'A straight path','Wise teaching calls for trust in God rather than relying only on personal understanding.',['trust','wisdom','paths']],
['lions','Daniel',6,'Prayer despite the decree','An official keeps praying despite a royal decree and is thrown to lions. God preserves his life.',['prayer','lions','decree']],
['fish','Jonah',2,'Prayer from the deep','A prophet prays from inside a great fish, recalling his distress and God’s deliverance.',['fish','prayer','deliverance']],
['beatitudes','Matthew',5,'A hillside teaching','Jesus announces blessings for the poor in spirit and the meek, and teaches about salt, light, and love for enemies.',['blessings','salt','light']],
['prayer','Matthew',6,'Hidden faithfulness','Jesus teaches about giving, prayer, fasting, treasure, and freedom from anxious striving.',['prayer','treasure','worry']],
['sower','Matthew',13,'Seeds and stories','Jesus tells stories about different soils, weeds among wheat, a mustard seed, and hidden treasure.',['soil','seed','treasure']],
['birth','Luke',2,'Good news to shepherds','A child is born in Bethlehem and laid in a manger. Shepherds hear an angelic announcement and visit.',['manger','shepherds','Bethlehem']],
['neighbour','Luke',10,'Mercy beside a road','Jesus tells of a wounded traveller helped by an unexpected neighbour, and visits two sisters.',['traveller','mercy','Samaritan']],
['lost','Luke',15,'Lost and found','Stories of a sheep, a coin, and a returning son show the joy of finding what was lost.',['sheep','coin','returning son']],
['nicodemus','John',3,'A conversation at night','A religious teacher visits Jesus, who speaks about new birth and God’s love for the world.',['night','new birth','love']],
['well','John',4,'Water and worship','Jesus speaks with a Samaritan woman at a well about living water and worship in spirit and truth.',['well','living water','worship']],
['vine','John',15,'Remain connected','Jesus pictures himself as a vine and his followers as branches, calling them to remain in him and love one another.',['vine','branches','love']],
['pentecost','Acts',2,'A community begins','The Spirit comes with signs of wind and fire. A sermon leads many to respond and share life together.',['Spirit','languages','community']],
['love','1 Corinthians',13,'The way of love','A passage explains that gifts and sacrifice without love are empty, then describes patient and kind love.',['patience','kindness','love']],
['fruit','Galatians',5,'Life by the Spirit','A letter contrasts works of the flesh with the fruit produced by the Spirit and calls people to walk by the Spirit.',['fruit','Spirit','freedom']],
['armor','Ephesians',6,'Ready to stand','A letter uses a belt, breastplate, shoes, shield, helmet, and sword to picture spiritual readiness.',['armour','stand firm','prayer']],
['faith','Hebrews',11,'Trust across generations','Many examples from Israel’s story show people acting in faith without yet seeing the complete promise.',['faith','promise','witnesses']]
].map(([id,book,chapter,title,summary,themes])=>({id,book,chapter,title,summary,themes,reference:`${book} ${chapter}`}));
