import {chapters} from './chapters.mjs';
const clone=s=>structuredClone(s);
const shuffled=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const values=new Uint32Array(1);crypto.getRandomValues(values);const j=values[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
const fail=message=>{throw new Error(message);};
export function validName(name){if(typeof name!=='string')fail('Choose a display name.');const v=name.trim().replace(/\s+/g,' ');if(v.length<2||v.length>24||/[<>\x00-\x1f]/.test(v))fail('Use a name of 2–24 characters.');return v;}
const player=(name,id,tokenHash,now)=>({id,name:validName(name),tokenHash,score:0,lastSeen:now,left:false,lastMessage:-10000});
export function createRoom(code,name,id,tokenHash,now,rounds=6){return {code,hostId:id,phase:'lobby',round:0,rounds:[4,6,8].includes(rounds)?rounds:6,players:[player(name,id,tokenHash,now)],deck:[],describerId:null,endsAt:0,guessed:[],eligible:[],messages:[],receipts:[],createdAt:now,expiresAt:now+21600000};}
export function joinRoom(room,name,id,tokenHash,now){const r=clone(room);if(r.players.filter(p=>!p.left).length>=8)fail('This room is full (8 players).');if(r.players.length>=24)fail('This room has reached its guest limit. Create a new room.');if(r.players.some(p=>!p.left&&p.name.toLowerCase()===String(name).trim().toLowerCase()))fail('That name is already in this room. Choose another.');r.players.push(player(name,id,tokenHash,now));r.messages.push({id:crypto.randomUUID(),type:'system',text:`${validName(name)} joined.`,at:now});r.messages=r.messages.slice(-60);return r;}
const numbers={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90,hundred:100};
export function normalizeGuess(text){let s=String(text).normalize('NFKC').toLowerCase().replace(/[-–]/g,' ').replace(/[^a-z0-9 ]/g,' ').replace(/\b(chapter|chap|ch)\b/g,' ').replace(/\bpsalms\b/g,'psalm').replace(/\bfirst\b/g,'1').replace(/\bsecond\b/g,'2').replace(/\bthird\b/g,'3');s=s.replace(/\b(twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety) (one|two|three|four|five|six|seven|eight|nine)\b/g,(_,a,b)=>numbers[a]+numbers[b]);s=s.replace(new RegExp('\\b('+Object.keys(numbers).join('|')+')\\b','g'),m=>numbers[m]);return s.replace(/\s+/g,' ').trim();}
export function forbiddenClue(text,card){const s=normalizeGuess(text),book=normalizeGuess(card.book).replace(/^\d /,'');return new RegExp(`\\b${book}\\b`).test(s)||new RegExp(`\\b${card.chapter}\\b`).test(s);}
function chapter(r){return chapters.find(c=>c.id===r.deck[r.round-1]);}
function reveal(r,reason){r.phase='reveal';r.reason=reason;return r;}
export function expireRound(room,now){const r=clone(room);if(r.phase==='playing'){if(now>=r.endsAt)return reveal(r,'Time is up.');const d=r.players.find(p=>p.id===r.describerId);if(!d||d.left||now-d.lastSeen>45000)return reveal(r,'The describer disconnected.');const available=r.eligible.filter(id=>r.players.some(p=>p.id===id&&!p.left));if(!available.length)return reveal(r,'No guessers remain in this round.');if(available.every(id=>r.guessed.includes(id)))return reveal(r,'Everyone found the chapter.');}return r;}
function begin(r,now){const active=r.players.filter(p=>!p.left&&now-p.lastSeen<=45000);if(active.length<2)fail('At least two connected players are needed.');r.round++;r.phase='playing';const previous=r.describerId;const currentIndex=active.findIndex(p=>p.id===previous);r.describerId=active[r.round===1?0:(currentIndex+1)%active.length].id;r.eligible=active.filter(p=>p.id!==r.describerId).map(p=>p.id);r.guessed=[];r.endsAt=now+90000;r.messages=[];r.reason='';r.players.forEach(p=>p.lastMessage=-10000);return r;}
export function applyAction(room,id,action,now){let r=clone(room);const p=r.players.find(p=>p.id===id);if(!p||p.left)fail('You have left this room. Join again to play.');const host=()=>{if(r.hostId!==id)fail('Only the host can do that.');};const active=()=>{if(r.phase!=='playing')fail('There is no active round.');};switch(action.type){
case 'heartbeat':p.lastSeen=now;return r;
case 'start':host();if(r.phase!=='lobby')fail('This game has already started.');r.deck=shuffled(chapters.map(c=>c.id)).slice(0,r.rounds);p.lastSeen=now;return begin(r,now);
case 'next':host();if(r.phase!=='reveal')fail('Wait for the round to finish.');if(r.round>=r.rounds){r.phase='finished';return r;}p.lastSeen=now;return begin(r,now);
case 'rematch':host();if(r.phase!=='finished')fail('Finish this game before a rematch.');r.phase='lobby';r.round=0;r.describerId=null;r.players.forEach(p=>p.score=0);r.deck=[];r.messages=[];return r;
case 'skip':host();active();return reveal(r,'The host ended this round.');
case 'claimHost':{const old=r.players.find(x=>x.id===r.hostId);if(old&&!old.left&&now-old.lastSeen<=45000)fail('The host is still connected.');r.hostId=id;p.lastSeen=now;return r;}
case 'leave':p.left=true;if(r.hostId===id){const next=r.players.find(x=>!x.left&&x.id!==id);if(next)r.hostId=next.id;}return expireRound(r,now);
case 'clue':case 'guess':{active();if(action.type==='clue'&&id!==r.describerId)fail('Only the describer can send clues.');if(action.type==='guess'&&(id===r.describerId||!r.eligible.includes(id)))fail('You cannot guess in this round.');if(r.guessed.includes(id)&&action.type==='guess')fail('You already guessed correctly.');if(now-p.lastMessage<700)fail('Give everyone a moment before sending again.');const text=typeof action.text==='string'?action.text.trim():'';if(!text||text.length>(action.type==='clue'?240:70))fail('Keep clues under 240 characters and guesses under 70.');const card=chapter(r);if(action.type==='clue'&&forbiddenClue(text,card))fail('Keep the book name and chapter number secret. Describe the events instead.');const correct=action.type==='guess'&&normalizeGuess(text)===normalizeGuess(card.reference);p.lastSeen=now;p.lastMessage=now;r.messages.push({id:crypto.randomUUID(),playerId:id,name:p.name,type:correct?'correct':action.type,text:correct?'Guessed correctly!':text,at:now});r.messages=r.messages.slice(-60);if(correct){p.score+=100;r.players.find(x=>x.id===r.describerId).score+=40;r.guessed.push(id);}return expireRound(r,now);}
default:fail('Unknown room action.');}}
export function roomView(room,id,now){const p=room.players.find(x=>x.id===id);if(!p||p.left)fail('You have left this room. Join again to play.');const card=chapter(room);const host=room.players.find(x=>x.id===room.hostId);const view={code:room.code,hostId:room.hostId,me:id,phase:room.phase,round:room.round,rounds:room.rounds,describerId:room.describerId,endsAt:room.endsAt,serverNow:now,expiresAt:room.expiresAt,reason:room.reason,players:room.players.filter(x=>!x.left).map(({id,name,score,lastSeen})=>({id,name,score,connected:now-lastSeen<=45000})),guessed:room.guessed,canGuess:room.phase==='playing'&&room.eligible.includes(id)&&!room.guessed.includes(id),canClaimHost:!host||host.left||now-host.lastSeen>45000,messages:room.messages};if(room.phase==='playing'&&id===room.describerId)view.secret=card;if(['reveal','finished'].includes(room.phase))view.answer=card;return view;}
